config/routes.rb
Rails.application.routes.draw do
  match "not_found", to: "errors#not_found", via: :all
  match "internal_server_error", to: "errors#internal_server_error", via: :all

  root 'home#index'
  get 'registers', to: 'registers#new'
  post 'registers', to: 'registers#create'
  get 'logins', to: 'logins#new'
  post 'logins', to: 'logins#create'
  delete 'logout', to: 'logins#destroy'
  
  get ':short_url', to: 'urls#get_url'

  resources :urls
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/url.rb
class Url < ApplicationRecord
    belongs_to :user
    has_many :url_tags, dependent: :destroy
    has_many :url_traces, dependent: :destroy

    validates :short_url, length: { maximum: 15 }
    validates :target_url, presence: true
    before_create :generate_short_url, :sanitize

    def generate_short_url
        rand(36**8).to_s(36)
    end
    
    def sanitize
        target_url.strip!
        sanitize_url = self.target_url.gsub(/(https?:\/\/)|(www\.)/, "")
        "http://#{sanitize_url}"
    end
end

app/models/url_tag.rb
class UrlTag < ApplicationRecord
    belongs_to :url

    validates :title, uniqueness: { scope: :url_id, message: "shouldn't duplicate" }
end

app/models/url_trace.rb
class UrlTrace < ApplicationRecord
    belongs_to :url

    reverse_geocoded_by :latitude, :longitude do |obj,results|
        if geo = results.first
            obj.address = geo.address
            obj.city = geo.city
            obj.state = geo.state
            obj.state_code = geo.state_code
            obj.postal_code = geo.postal_code
            obj.country = geo.country
            obj.country_code = geo.country_code
        end
    end
      
    after_validation :reverse_geocode
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :urls

    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    before_action :set_hostname

    private
    def set_current_user
        @_current_user ||= session[:current_user_id] && User.find_by(id: session[:current_user_id])
        @user_decorator = helpers.decorate(@_current_user) unless @_current_user.nil?
    end

    private
    def set_hostname
        @hostname = ENV.fetch("RAILS_ENV", "development") == "development" ? request.host_with_port : request.host
    end

    def logged_in?
        !!@_current_user
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
    def not_found
        render status: 404
    end
  
    def internal_server_error
        render status: 500
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
    def new
        if logged_in?
            flash[:notice] = "You are already login."
            redirect_to root_url
        end
    end

    def create
        user = User.find_by(email: params[:email])

        if user.present? && user.authenticate(params[:password])
            session[:current_user_id] = user.id
            redirect_to root_path, notice: 'Logged in successfully'
        else
            redirect_to :logins, notice: "Invalid email or Wrong password"
        end
    end

    def destroy
        session.delete(:current_user_id)
        @_current_user = nil
        flash[:notice] = "You have successfully logged out."
    end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
    def new
        if logged_in?
            flash[:notice] = "You are already login."
            redirect_to root_url
        end
        
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:current_user_id] = @user.id
            redirect_to root_path, notice: 'Successfully created account'
        else
            render :new
        end
    end

    private
    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password_confirmation, :password)
    end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
    before_action :set_url, only: [:update, :edit, :show, :destroy]
    before_action :set_coordinates, only: [:show, :get_url]

    def new
        @url = Url.new
    end

    def show
        @daily_visits = @url.url_traces.group_by_day(:created_at)
        @visit_no_by_countries = @url.url_traces.where.not(country: nil).group(:country)
    end

    def edit
        @url_tag_titles = @url.url_tags.pluck(:title)
    end

    def create
        @url = Url.new(url_params)

        user_id = @_current_user.id

        @url.user_id = user_id
        @url.short_url = @url.generate_short_url
        
        if @url.save
            redirect_to root_path, notice: 'Successfully created new link'
        else
            flash[:error] = @url.errors.full_messages
            redirect_to new_url_path
        end
    end

    def update
        target_url = url_params[:target_url]

        if @url.update(target_url: target_url)
            tags = url_params[:tags] || []

            UrlTag.where(url_id: @url.id).delete_all

            tags.each do |tag|
                @url.url_tags.create(title: tag)
            end

            redirect_to root_path, notice: 'Successfully updated new link'
        else
            flash[:error] = @url.errors.full_messages
            redirect_to edit_url_path
        end
    end

    def destroy
        Url.where(id: @url.id).destroy_all

        flash[:notice] = 'Successfully deleted url'
    end

    def get_url
        @url = Url.find_by(short_url: params[:short_url])

        if @url.blank?
            redirect_to '/not_found'
        else
            UrlTracker.call(@url, @longitude, @latitude)

            redirect_to @url.sanitize, allow_other_host: true
        end
    end

    private
    def url_params
        params.require(:url).permit(:target_url, tags: [])
    end

    def set_url
        @url = Url.find(params[:id])
    end

    def set_coordinates
        location = request.location
        @longitude = location.longitude
        @latitude = location.latitude
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def decorate(model, decorate_class = nil)
        (decorate_class || "#{model.class}Decorator".constantize).new(model)
    end
end

app/views/home/index.html.erb
<%= render 'shared/navbar'%>

<div class="container">
    <% if @_current_user != nil %>
        <%= render 'shared/urls'%>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/logins/new.html.erb
<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-12">
                <a href="<%= root_path %>">
                    <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Back
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3>Sign in</h3>
                    </div>
                    <div class="panel-body">
                        <%= form_with url: logins_path, html: { class: "form-row" } do |f| %>
                            <div class="form-group">
                                <%= f.label 'email:'%><br>
                                <%= f.text_field :email, id: 'email', class: "form-control" %>
                            </div>
                            <div class="form-group">
                                <%= f.label 'password:'%><br>
                                <%= f.password_field :password, id: 'password', class: "form-control" %>
                            </div>
                            <div class="form-group">
                                <%= f.submit 'Sign in', class: "btn btn-default" %>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/registers/new.html.erb
<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-12">
                <a href="<%= root_path %>">
                    <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Back
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3>Register</h3>
                    </div>
                    <div class="panel-body">
                        <%= form_with model: @user, url: registers_path, html: { class: "form-row" } do |f| %>
                            <div class="form-group">
                                <%= f.label 'first name:'%><br>
                                <%= f.text_field :first_name, id: 'first_name', class: "form-control" %>
                            </div>
                            <div class="form-group">
                                <%= f.label 'last name:'%><br>
                                <%= f.text_field :last_name, id: 'last_name', class: "form-control" %>
                            </div>
                            <div class="form-group">
                                <%= f.label 'email:'%><br>
                                <%= f.text_field :email, id: 'email', class: "form-control" %>
                            </div>
                            <div class="form-group">
                                <%= f.label 'password:'%><br>
                                <%= f.password_field :password, id: 'password', class: "form-control" %>
                            </div>
                            <div class="form-group">
                                <%= f.submit 'Register', class: "btn btn-default" %>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header" data-controller="navbar">
            <a class="navbar-brand" href="#">CoinGecko URL Shortener</a>
            <% if @_current_user != nil %>
                <p class="navbar-text">Signed in as
                    <%= @user_decorator.full_name %>
                </p>
                <a href="/urls/new" type="button" class="btn btn-default navbar-btn">Create Link</a>
                <button data-action="click->navbar#logout" type="button" class="btn btn-default navbar-btn">Logout</button>
            <% else %>
                <a href="/logins" type="button" class="btn btn-default navbar-btn">Sign in</a>
                <a href="/registers" type="button" class="btn btn-default navbar-btn">Register</a>
            <% end %>
        </div>
    </div>
</nav>

app/views/shared/_urls.html.erb
<ul class="list-group row" data-controller="home">
    <% @_current_user.urls.each do |url| %>
        <div class="col-md-1">
            <button 
                type="button"
                class="btn btn-primary btn-sm btn-block"
                data-action="click->home#copyLink"
                data-home-short-url-param="<%= @hostname + "/" + url.short_url %>"
            >
                Copy Url
            </button>
            <a class="btn btn-warning btn-sm btn-block" href="<%= edit_url_path(url.id)%>">
                Edit
            </a>
            
            <button
                type="button"
                class="btn btn-danger btn-sm btn-block"
                data-action="click->home#deleteUrl"
                data-home-id-param="<%= url.id %>"
            >
                Delete
            </button>
        </div>
        <div class="col-md-11">
            <a href="<%= url_path(url.id)%>" class="list-group-item">
                <div class="short-url-container">
                    <h4 class="list-group-item-heading">
                        <%= "/" + url.short_url %>
                    </h4>
                </div>
                <h5>Target Url: <span class="label label-primary"><%= url.target_url %></span></h5>
                <h5>Clicks: <span class="label label-default"><%= url.clicks %></span></h5>
                <div>
                    <% url.url_tags.each do |tag| %>
                        <span class="label label-success"><%= tag.title %></span>
                    <% end %>
                </div>
            </a>
        </div>
    <% end %>
</ul>

app/views/urls/edit.html.erb
<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-12">
                <a href="<%= root_path %>">
                    <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Back
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3>Edit Page</h3> 
                    </div>
                    <div class="panel-body">
                        <div class="urls" data-controller="urls" data-urls-tags-data-value="<%= @url_tag_titles %>">
                            <%= form_with model: @url, url: url_path, method: :put, html: { 'data-urls-target': 'form', class: "form-row" } do |f| %>
                                <div class="form-group">
                                    <%= f.number_field :id, id: 'id', type: :hidden %>
                                    <%= f.label 'Enter Target Url:' %><br>
                                    <%= f.text_field :target_url, id: 'target_url', class: "form-control" %>
                                </div>
                                <div class="form-group">
                                    <div class="tags">
                                        <%= f.label 'Tags:'%><br>
                                        <input
                                            id="tag_title"
                                            class="form-control"
                                            type="text"
                                            name="url[tag_title]"
                                            data-action="keypress->urls#tagInputOnKeyPress"
                                            data-urls-target="tagInput"
                                            placeholder="Press enter to add tag"
                                        />
                                        <ul class="nav" role="tablist" data-urls-target="tagsList">
                                            <% @url.url_tags.each do |url_tag| %>
                                                <li>
                                                    <span class="badge" data-urls-target="tagData" data-urls-tag-value="<%= url_tag.title %>">
                                                        <%= url_tag.title %>
                                                        <a class="glyphicon glyphicon-remove"
                                                            style="color: white" data-action="click->urls#tagDeleteOnClick" data-urls-text-value-param="<%= url_tag.title %>">
                                                        </a>
                                                    </span>
                                                    <input type="hidden" value="<%= url_tag.title%>" name="url[tags][]">
                                                </li>
                                            <% end %>
                                        </ul>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <button type="button" class="btn btn-default" data-action="click->urls#onSubmit">
                                        Save
                                    </button>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/urls/new.html.erb
<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-12">
                <a href="<%= root_path %>">
                    <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Back
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3>Create Page</h3>
                    </div>
                    <div class="panel-body">
                        <%= form_with model: @url, url: urls_path, html: { class: "form-row" } do |f| %>
                            <div class="form-group">
                                <%= f.label 'Enter Target Url:'%><br>
                                <%= f.text_field :target_url, id: 'target_url', class: "form-control" %>
                            </div>
                            <div class="form-group">
                                <%= f.submit 'Save', class: "btn btn-default" %>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/urls/show.html.erb
<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-12">
                <a href="<%= root_path %>">
                    <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Back
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <div>
                    <h5>Total Clicks: </h5>
                    <span class="label label-info"><%= @url.clicks %></span>
                </div>
                <div>
                    <h5>Latest visited time: </h5>
                    <% if @url.url_traces.count > 0 %>
                        <span class="label label-info"><%= @url.url_traces.order(:created_at).last.created_at.to_fs(:long_ordinal) %></span>
                    <% else %>
                        <span class="label label-info">N/A</span>
                    <% end %>
                </div>
                <div>
                    <div class="row">
                        <div class="col-md-12">
                            <h5>Top 3 countries: </h5>
                            <% if @url.url_traces.count > 0 %>
                                <ul class="list-unstyled">
                                    <% @visit_no_by_countries.count.sort_by {|k, v| -v}.first(3).each do |data| %>
                                        <li class="list-unstyled-item">
                                            <%= data[0]%>
                                            <span class="badge"><%= data[1]%></span>
                                        </li>
                                    <% end %>
                                </ul>
                            <% else %>
                                <span class="label label-info">N/A</span>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-10">
                <div class="chart-container">
                    <%= column_chart @daily_visits.count, id: "daily-visit-chart", ytitle: "Clicks" %>
                </div>
            </div>
        </div>
    </div>
</div>